name: Build and deploy

on: [push]

jobs:
  job1: 
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      DATABASE_NAME: ${{secret.DATABASE_NAME}}
      DATABASE_HOSTNAME: ${{secret.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secret.DATABASE_PORT}}
      DATABASE_USERNAME: ${{secret.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secret.DATABASE_PASSWORD}}
      SECRET_KEY: ${{secret.SECRET_KEY}}
      ALGORITHM: ${{secret.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secret.ACCESS_TOKEN_EXPIRE_MINUTES}}
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Setting up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: tests with pytest
        run: |
          pip install pytest
          pytest