name: Build and deploy

on: [push]

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Setting up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: tests with pytest
        run: |
        pip install pytest
        pytest